
package com.Students;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2016-12-28T13:27:05.573+05:30
 * Generated source version: 2.5.1
 * 
 */
public final class GetAllData_Localhost_Client {

    private static final QName SERVICE_NAME = new QName("urn:getStudentsData", "myEmployeeService");

    private GetAllData_Localhost_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = MyEmployeeService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        MyEmployeeService ss = new MyEmployeeService(wsdlURL, SERVICE_NAME);
        GetAllData port = ss.getLocalhost();  
        
        {
        System.out.println("Invoking getAllEmployees...");
        java.lang.String _getAllEmployees_myType = "";
        com.Students.EmployeesCollection _getAllEmployees__return = port.getAllEmployees(_getAllEmployees_myType);
        System.out.println("getAllEmployees.result=" + _getAllEmployees__return);


        }

        System.exit(0);
    }

}
