package com.Students;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2016-12-28T13:27:05.593+05:30
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "urn:getStudentsData", name = "getAllData")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GetAllData {

    @WebMethod(action = "urn:getStudentsData/getAllEmployees")
    @WebResult(name = "employeeResponse", targetNamespace = "", partName = "employeeResponse")
    public EmployeesCollection getAllEmployees(
        @WebParam(partName = "myType", name = "myEMP", targetNamespace = "http://www.example.org")
        java.lang.String myType
    );
}
