package com.Students;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2016-12-28T13:27:05.603+05:30
 * Generated source version: 2.5.1
 * 
 */
@WebServiceClient(name = "myEmployeeService", 
                  wsdlLocation = "file:/D:/mulesoftWorkspace/sharangdb/src/main/resources/getStudentsData.wsdl",
                  targetNamespace = "urn:getStudentsData") 
public class MyEmployeeService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:getStudentsData", "myEmployeeService");
    public final static QName Localhost = new QName("urn:getStudentsData", "localhost");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/mulesoftWorkspace/sharangdb/src/main/resources/getStudentsData.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MyEmployeeService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/mulesoftWorkspace/sharangdb/src/main/resources/getStudentsData.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MyEmployeeService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MyEmployeeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyEmployeeService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MyEmployeeService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MyEmployeeService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MyEmployeeService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns GetAllData
     */
    @WebEndpoint(name = "localhost")
    public GetAllData getLocalhost() {
        return super.getPort(Localhost, GetAllData.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetAllData
     */
    @WebEndpoint(name = "localhost")
    public GetAllData getLocalhost(WebServiceFeature... features) {
        return super.getPort(Localhost, GetAllData.class, features);
    }

}
